#!/usr/bin/env node
/**
 * Creates a local .env (and .env.local) so demo login works out of the box.
 * Does not overwrite existing secrets unless --force is passed.
 */
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const force = process.argv.includes("--force");

function parseEnv(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function serializeEnv(values) {
  return `# Synapse local environment — generated by npm run setup
# Safe for demo login. Add Google/OpenAI keys later when you want live data.

DATABASE_URL="${values.DATABASE_URL}"
AUTH_SECRET="${values.AUTH_SECRET}"
AUTH_URL="${values.AUTH_URL}"
NEXTAUTH_URL="${values.NEXTAUTH_URL}"

# Leave empty for demo-only. Fill to enable "Continue with Google".
AUTH_GOOGLE_ID="${values.AUTH_GOOGLE_ID}"
AUTH_GOOGLE_SECRET="${values.AUTH_GOOGLE_SECRET}"

# Leave empty while DEMO_MODE=true. Jarvis still answers with demo timeline tools.
OPENAI_API_KEY="${values.OPENAI_API_KEY}"

# true = sample school data + demo Jarvis replies (recommended until keys are ready)
DEMO_MODE="${values.DEMO_MODE}"
`;
}

const envPath = resolve(root, ".env");
const localPath = resolve(root, ".env.local");
const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {};

const placeholderSecrets = new Set([
  "",
  "replace-with-a-long-random-secret",
  "changeme",
]);

const needsSecret =
  force ||
  !existing.AUTH_SECRET ||
  placeholderSecrets.has(existing.AUTH_SECRET);

const values = {
  DATABASE_URL: existing.DATABASE_URL || "file:./dev.db",
  AUTH_SECRET: needsSecret
    ? randomBytes(32).toString("base64")
    : existing.AUTH_SECRET,
  AUTH_URL: existing.AUTH_URL || existing.NEXTAUTH_URL || "http://localhost:3000",
  NEXTAUTH_URL:
    existing.NEXTAUTH_URL || existing.AUTH_URL || "http://localhost:3000",
  AUTH_GOOGLE_ID: existing.AUTH_GOOGLE_ID || "",
  AUTH_GOOGLE_SECRET: existing.AUTH_GOOGLE_SECRET || "",
  OPENAI_API_KEY: existing.OPENAI_API_KEY || "",
  DEMO_MODE: existing.DEMO_MODE || "true",
};

if (!force && existsSync(envPath) && !needsSecret) {
  console.log("✓ .env already has AUTH_SECRET — left as-is (use --force to regenerate)");
} else {
  writeFileSync(envPath, serializeEnv(values));
  console.log(`✓ Wrote ${envPath}`);
}

// Next.js also reads .env.local; keep them aligned for local demo.
writeFileSync(localPath, serializeEnv(values));
console.log(`✓ Wrote ${localPath}`);
console.log("");
console.log("Demo login is ready after DB migrate:");
console.log("  npx prisma migrate dev --name init");
console.log("  npm run dev");
console.log("Then open http://localhost:3000/login → Enter as demo student");
